### ISSUE TITLE
IE9 error: Expected ':'

### ISSUE THREAD

**Issue by BaptisteBriel** [bigwheel-framework/bw-vm#3]
Hello people of Jam3,

I just had an error with bw-vm running on IE9. (although i'm not sure if it's supported...)

![](https://cloud.githubusercontent.com/assets/2464663/7727955/8ca49060-ff0c-11e4-9ab5-0804b63c8359.png)

I don't understand the two functions get & set and the way it's written.

![](https://cloud.githubusercontent.com/assets/2464663/7727972/b94ee8ae-ff0c-11e4-95b8-818a7c8dac03.png)

Shouldn't be something like this ?

![](https://cloud.githubusercontent.com/assets/2464663/7728380/38f8f5ca-ff0f-11e4-841d-94ac8021f33e.png)

Thanks for your time.

**Comment by MikkoH** [comment]
@BaptisteBriel Nice catch. I think the getters and setters should actually be define through:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

This is what ie supports quite far back. Hmmm... Have to see when I find the time to fix. Feel free to do a pull request if you have time to fix.

**Comment by cheapsteak** [comment]
Perhaps run source through Babel to convert `get property()` to `defineProperty`?  
The get syntax does look much nicer

**Comment by BaptisteBriel** [comment]
I could run the source through Babel to convert the code, but still have some issues on IE9.

I get errors like: Object doesn't support property or method 'call'

I added a polyfill that fixed this error (https://github.com/es-shims/es5-shim), but now I have this one: Object doesn't support property or method 'defineProperty'

I have to be honest, I don't really understand why I get this error. Isn't 'Object.defineProperty' supposed to work on IE9? http://kangax.github.io/compat-table/es5/

**Comment by BaptisteBriel** [comment]
Oh, my bad... I don't have the errors with this meta tag in the <head> :

<meta http-equiv="X-UA-Compatible" content="IE=edge">

...but still doesn't work. I'll try to find why today to make bigwheel work on IE9.

**Comment by MikkoH** [comment]
Ok cool. Thanks. It's my mistake I used that syntax. It should be using `Object.defineProperty`. Sorry...
